name: Frontend CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: docker build -f frontend/Dockerfile --target test -t arx_frontend:test frontend

      # Run Lint
      - name: Run lint
        run: docker run --rm arx_frontend:test npm run lint

      # Run Tests
      - name: Run tests
        run: docker run --rm arx_frontend:test npm run test

      # Run Build
      - name: Run build
        run: docker run --rm arx_frontend:test npm run build